title: Taylor Learns
email: t@taylorlearns.com
description: >
  I build digital solutions that make lives easier and more productive. Check out my projects and blog posts.
baseurl: ''
url: 'https://taylorlearns.com'

# Collections configuration
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:path/

# Default configuration
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Include directories
include:
  - pages
  - _posts
  - _projects
  - assets

# Exclude directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .jekyll-cache

github_username: taylorlearns
markdown: kramdown
excerpt_separator: <!--more-->

